class MatchvsMessage {
	/**
	 * 定义了Matchvs非对战消息网络事件
	 */
	public static MATCHVS_INIT = "MATCHVS_INIT";  
	public static MATCHVS_REGISTERUSER = "MATCHVS_REGISTERUSER";
	public static MATCHVS_LOGIN = "MATCHVS_LOGIN";
	public static MATCHVS_JOINROOM_RSP = "MATCHVS_JOINROOM_RSP";
	public static MATCHVS_JOINROOM_NOTIFY = "MATCHVS_JOINROOM_NOTIFY";
	public static MATCHVS_CREATE_ROOM = "MATCHVS_CREATE_ROOM";
	public static MATCHVS_LEVAE_ROOM_NOTIFY = "MATCHVS_LEVAE_ROOM_NOTIFY";
	public static MATCHVS_LEVAE_ROOM = "MATCHVS_LEVAE_ROOM";
	public static MATCHVS_KICK_pLAYER = "MATCHVS_KICK_pLAYER";
	public static MATCHVS_KICK_PLAYER_NOTIFY = "MATCHVS_KICK_PLAYER_NOTIFY";

	public constructor() {
	}
}