class MatchvsMessage {
	/**
	 * 定义了Matchvs非对战消息网络事件
	 */
	public static MATCHVS_INIT = "MATCHVS_INIT";  
	public static MATCHVS_REGISTERUSER = "MATCHVS_REGISTERUSER";
	public static MATCHVS_LOGIN = "MATCHVS_LOGIN";
	public static MATCHVS_JOINROOM_RSP = "MATCHVS_JOINROOM_RSP";
	public static MATCHVS_JOINROOM_NOTIFY = "MATCHVS_JOINROOM_NOTIFY";
	public static MATCHVS_CREATE_ROOM = "MATCHVS_CREATE_ROOM";
	public static MATCHVS_LEVAE_ROOM_NOTIFY = "MATCHVS_LEVAE_ROOM_NOTIFY";
	public static MATCHVS_LEVAE_ROOM = "MATCHVS_LEVAE_ROOM";
	public static MATCHVS_KICK_PLAYER = "MATCHVS_KICK_PLAYER";
	public static MATCHVS_KICK_PLAYER_NOTIFY = "MATCHVS_KICK_PLAYER_NOTIFY";
	public static MATCHVS_ROOM_DETAIL_RSP = "MATCHVS_ROOM_DETAIL_RSP";
	public static MATCHVS_RANK_LIST = "MATCHVS_RANK_LIST";
	public static MATCHVS_DELET_TIME = "MATCHVS_DELET_TIME";
	public static MATCHVS_ERROR = "MATCHVS_ERROR";
	public static MATCHVS_NETWORKSTATE = "MATCHVS_NETWORKSTATE";
	public static MATCHVS_SEND_EVENT_RSP = "MATCHVS_SEND_EVENT_RSP";
	public static MATCHVS_SEND_EVENT_NOTIFY = "MATCHVS_SEND_EVENT_NOTIFY";

	public constructor() {
	}
}